#!/usr/bin/env python

import sys
import requests
import json

MIBZ_URL = "http://mibz.org/by-node/%s" % (sys.argv[1])

mib_string = requests.get(MIBZ_URL).text
print mib_string
mib_list = json.loads(mib_string)

print mib_list